### PR TITLE
Function enhancement

### PR DESCRIPTION
**Pull request by lazyoop**
# Functional enhancements

Introduction: I am just a programming amateur. These newly added functions may seem very confusing.

### introduce:<br />
Simple support for rabbitmq, currently only supports the Publish/Subscribe model of amqp, where the switch uses the default one of rabbitmq.

### **How to use:**<br />
Create a vhost, for example: `magnetico`.

Fill in the database address like this
`amqp://name:password@localhost:port/magnetico`
<br>After starting, you will see it in the rabbitmq gui interface:

image

`hello` is used to test the connectivity with rabbitmq,<br />
`magnet_data` contains byte type metadata.

### introduce:<br />
This feature allows to specify the communication port for bootstrapNodes at program startup.
### **How to use:**<br />
When starting, pass in the `--is-bootstrap-node-self-port` parameter and the `--bootstrap-node=xxx:port` parameter to use the specified communication port.

For example: `magntico --is-bootstrap-node-self-port --bootstrap-node=router.bittorrent.com:6881`

If you do not want to use the specified port function, pass in the `--bootstrap-node=router.bittorrent.com` parameter like this.

### introduce:<br />
Configuration files can be loaded from yaml files.

### **How to use:**<br />
**Required parameters:** Pass at least `--with-config-file` when starting.<br/>
**Optional parameter:** `--config-file-path` specifies the path to the yaml configuration file. If you do not fill in this parameter, it will default to the config.yml file under the program for loading.

For example: `magnetico --with-config-file or magnetico --with-config-file --config-file-path=/con/file/path/run.yml`

config.yml:
```
databaseURL: "amqp://rabbitmq:rabbitmq@localhost:5672/magnetico"
indexerAddrs: "0.0.0.0:0"
indexerMaxNeighbors: 600
leechMaxN: 700
maxRPS: 600
bootstrappingNodes: "dht.libtorrent.org:25401,dht.transmissionbt.com:6881,router.bittorrent.com:6881,router.utorrent.com:6881,dht.aelitis.com:6881"
bootstrapNodesSelfPort: true
filterNodesCIDRs: ""
addr: "0.0.0.0:8965"
cred: ""
runDaemon: true
runWeb: false
```

### CODE REVIEW

**Comment by tgragnato** [comment]
Hi @lazyoop,

Thank you so much for your contribution! Don't worry about being a programming amateur; your work is greatly appreciated and my feedback is mostly positive.

Before merging your feature, I would like to adapt it to the project's style, which might take a little time. Thanks for your understanding and patience!

**Comment by lazyoop** [comment]
OK, thanks

**Review by tgragnato — APPROVED** [review]

**Comment by lazyoop** [comment]
https://github.com/lazyoop/magnetico-new/commit/9f37c7d3d5486c06627f230f9b22750a1bc37d25

**Comment by tgragnato** [comment]
I separated the features into different pull requests, isolating unrelated changes from one another, and created atomic commits to make reviewing the changes easier and more effective.

1. [feat(persistence): add rabbitmq amqp basic support](https://github.com/tgragnato/magnetico/pull/515)
2. [feat!: allow user supplied ports for bootstrap nodes](https://github.com/tgragnato/magnetico/pull/521)
3. [feat!: introduce the ability to use a configuration file](https://github.com/tgragnato/magnetico/pull/522)

A well-defined PR allows for more targeted testing. It becomes simpler to isolate and resolve issues related to a specific change.
If a PR introduces a problem, rolling it back is straightforward without affecting other unrelated changes.

Atomic commits clearly document the logical steps of development, making the code easier to understand in the future.
A clean history simplifies integration and collaboration within the team.
Specifically, the project is following the [conventional commits standard](https://www.conventionalcommits.org/en/v1.0.0/).

While doing this, I was able to introduce unit tests, improving codebase coverage, and minimise the dependencies introduced. I hope this will also help make the code more robust and maintainable.

**Comment by tgragnato** [comment]
No need to apologize! The workload on the project is manageable, and I genuinely appreciate PRs. It’s great to see contributions!

As you may have noticed, I tend to be quite opinionated (some of my coding practices might come across as a bit unconventional), so I would likely refactor the code regardless. Collaboration like this only makes the project stronger.

Thank you!

**Pull request merged**
